name: Check need info

on:
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  check-need-info:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'question'
          inactive-day: 7
          body: |
            Hello @${{ github.event.issue.user.login }}, this issue was closed due to no activities in 7 days.
            你好 @${{ github.event.issue.user.login }}，此issue因超过7天未回复被关闭。