name: release

on:
  push:
    tags:
      - '*'

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
  release:
    needs: changelog
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.18]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v2
          path: alist
          persist-credentials: false
          fetch-depth: 0

      - name: Install upx
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          mv alist/build.sh .
          bash build.sh cdn
          mv dist/* alist/public
          bash build.sh release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: alist/build/compress/*